name: Python Pytest Testing

on:
    pull_request: 
        branches: 
            - develop
            - live

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the repo           # Checkout the repository
              uses: actions/checkout@v3         
            - name: Set up Python               # Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.x' 
            - name: Install dependicies        # Install pip requirements
              run:
                python -m pip install --r upgrade pip
                pip install -r requirements.txt
            - name: Run pytest                  # Run pytest
              run: pytest